# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 99

    [main.params]
    icon = "rss"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/SisypheOvO"

    [social.params]
        icon = "brand-github"
